### ISSUE TITLE
"NameError: name 'keras' is not defined" when loading model weights (transunet, swin-unet)

### ISSUE THREAD

**Issue by bsariturk** [yingkaisha/keras-unet-collection#39] opened 2021-12-30 14:17 UTC
I've saved the trained model, using "model.save(filepath, save_traces=True)" like in the guide. But when I try to load the model weights using "utils.dummy_loader" I get this error and I've already imported keras. Anybody got a solution for that? Or generally to load models/model weights.

Edit: I solved the load problem using "custom_objects" to import custom layers with load_model.

**Comment by yingkaisha** [comment] 2022-01-10 22:33
Hi, thank you for your feedback. The problem is fixed in the new release: `pip install keras-unet-collection==0.1.13`

**Closed** 2022-01-26 22:41 UTC
Labels: bug
